In [64]:
from PIL import Image
import numpy as np
#a=int(input("enter the nummber to be added in the pixel"))
img=Image.open("flowers.jpg")
print(img)
#img.show()
pix_val=np.array(img.getdata())
print(pix_val)
#print(len(pix_val[0]))
for row in range(len(pix_val)):
    #for col in range(len(pix_val[0])):
      #  print(str(pix_val[row][col]))
    pix_val[row][0]= 100 + pix_val[row][0]
    #print(pix_val[row][0])
    pix_val[row][1]= 100 + pix_val[row][1]
    pix_val[row][2]= 100 + pix_val[row][2]
#pix_val[row][col]=np.array[[pix_val[row][0],pix_val[row][1],pix_val[row][2]]]
img.save("flowers.jpg")
#img=Image.open("flowers.jpg",'r')
#pix_val=np.array(img.getdata())
print(pix_val[row][0])
#print(img)

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=275x183 at 0x59D5C88>
[[210 142  81]
 [210 142  81]
 [212 141  79]
 ...
 [ 94 140   8]
 [ 94 140   8]
 [ 94 140   8]]
194


In [70]:
from PIL import Image
img=Image.open("flowers.jpg")
pixels=img.load()
#print(pixels)
#print(img.size[0])
for i in range(img.size[0]):
    for j in range(img.size[1]):
        pixels[i,j]=(i,j,100)
img.show()