In [2]:
from PIL import Image
import numpy as np
#a=int(input("enter the nummber to be added in the pixel"))
img=Image.open("flowers.jpg")
print(img)
pix_val=np.array(img.getdata())
print(pix_val)
#print(len(pix_val[0]))
for row in range(len(pix_val)):
    #for col in range(len(pix_val[0])):
      #  print(str(pix_val[row][col]))
    pix_val[row][0]= 255-  pix_val[row][0]
    #print(pix_val[row][0])
    pix_val[row][1]= 255-  pix_val[row][1]
    pix_val[row][2]= 255- pix_val[row][2]
#pix_val[row][col]=np.array[[pix_val[row][0],pix_val[row][1],pix_val[row][2]]]
img.save("flowers.jpg")
#img=Image.open("flowers.jpg",'r')
#pix_val=np.array(img.getdata())
for row in range(len(pix_val)):
    print(pix_val[row][0])
#print(img)

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=275x183 at 0x562F9B0>
[[210 142  81]
 [210 142  81]
 [212 141  79]
 ...
 [ 94 140   8]
 [ 94 140   8]
 [ 94 140   8]]
45
45
43
40
37
32
28
22
17
13
11
11
11
11
12
12
10
15
19
17
13
11
14
17
24
27
30
34
37
37
36
35
31
31
30
30
31
31
31
34
29
31
32
32
33
32
33
33
25
25
24
22
18
14
11
11
11
14
16
15
13
11
11
9
25
22
16
11
8
7
7
7
2
1
0
1
0
0
0
0
7
5
3
0
0
0
0
0
2
3
6
7
6
4
4
2
1
3
4
5
6
6
7
5
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
14
12
8
4
3
4
8
10
18
22
24
28
32
36
37
39
58
62
67
76
86
96
104
112
115
117
116
116
113
109
107
106
90
91
93
94
92
86
79
73
72
66
60
54
49
44
42
39
36
35
33
31
29
25
23
19
24
21
19
17
18
20
25
28
43
42
44
43
45
49
52
56
61
63
63
64
65
65
64
64
71
69
66
63
58
55
51
49
44
43
39
33
29
23
19
18
19
17
15
13
10
8
8
9
12
16
17
21
21
22
23
24
28
28
30
32
36
38
41
42
41
41
41
42
41
42
40
40
47
47
47
47
47
47
47
47
47
47
47
46
46
45
45
45
39
39
39
50
48
47
43
40
36
29
25
20
16
14
13
13
14
15
15
14
18
21
21
1

88
79
69
64
60
49
47
43
39
35
34
34
34
30
31
32
35
38
40
43
44
39
40
41
43
42
38
32
27
30
29
27
24
19
13
9
4
7
8
6
6
4
3
4
4
4
5
5
4
2
1
1
0
3
3
3
2
2
1
1
3
1
3
3
4
6
5
6
6
17
19
18
20
21
22
25
27
25
27
28
30
30
32
33
33
38
38
38
38
39
39
39
40
40
41
42
43
44
45
46
46
44
44
44
89
89
87
86
85
85
83
82
80
79
78
78
79
80
79
79
83
84
85
86
87
88
87
87
87
88
89
91
93
95
97
98
102
101
99
96
92
90
88
89
90
89
86
82
77
72
68
66
59
57
55
52
51
47
44
42
38
36
32
27
22
17
15
13
10
10
10
10
10
9
7
5
7
4
3
2
2
3
3
3
7
7
5
4
2
4
4
3
11
9
7
4
4
3
4
5
13
11
10
8
7
6
4
3
4
4
4
4
5
5
7
7
1
1
2
2
2
3
5
10
4
6
7
7
5
4
2
2
5
5
5
4
4
3
2
1
2
2
3
5
8
10
11
12
23
25
28
31
38
43
49
57
71
82
94
104
109
110
109
107
113
116
120
124
127
126
124
122
114
110
101
92
83
72
65
62
50
48
43
40
37
35
36
34
32
32
34
35
38
41
44
44
43
45
46
46
44
40
34
28
30
27
24
21
16
10
4
0
7
7
5
4
3
1
1
1
4
4
3
2
2
0
0
0
0
0
0
0
0
0
0
2
0
0
2
4
3
4
5
5
17
19
18
20
21
22
23
26
23
25
27
28
29
29
29
29
37
37
37
38
38
38
39
39
40
40
42
43
4

68
66
61
58
61
60
60
60
58
57
57
55
48
47
45
43
42
41
39
39
36
37
35
35
35
34
31
31
31
29
30
29
30
31
32
32
27
29
32
35
37
37
34
33
32
33
35
36
38
40
41
42
45
44
43
42
39
38
37
36
33
33
33
31
31
31
31
31
25
25
25
24
22
21
21
20
16
15
15
12
12
11
10
10
7
7
8
8
9
12
13
14
18
20
25
31
37
40
43
47
53
54
56
59
64
66
69
70
65
61
57
52
49
47
46
47
38
36
35
32
28
23
21
19
14
9
5
2
2
3
6
8
0
2
5
8
9
8
8
7
1
1
2
0
0
0
1
2
10
9
10
10
13
15
16
14
8
3
3
3
5
8
10
12
9
8
7
6
4
3
4
4
5
7
7
5
5
4
2
1
1
2
1
0
1
0
3
5
1
3
3
4
3
1
0
0
0
0
0
0
0
0
0
2
5
7
10
13
14
15
16
16
25
25
26
26
29
30
32
34
38
39
38
39
43
47
52
55
63
72
79
90
90
91
91
92
93
94
94
94
94
94
94
94
94
94
94
95
95
95
94
93
92
92
91
91
89
86
84
84
86
89
91
87
83
78
72
70
67
68
68
69
70
72
73
70
66
64
61
64
63
63
62
61
60
59
56
52
50
48
46
44
44
42
42
39
40
38
38
39
37
36
35
37
35
35
35
36
36
37
36
31
34
36
40
41
39
38
37
41
42
43
45
47
48
48
50
47
46
45
44
43
41
40
39
36
36
36
36
35
35
35
35
28
28
28
26
26
25
23
23
18
18
16
16
14
13
13
13


13
12
13
12
12
12
11
13
15
14
13
13
14
16
20
22
18
21
26
30
32
30
25
19
22
19
17
16
15
12
8
6
12
8
6
4
0
0
0
0
0
3
5
5
5
5
5
4
9
7
5
1
1
0
0
1
0
0
0
0
1
4
7
8
17
21
24
30
34
41
45
49
50
52
54
56
59
62
64
65
65
67
70
57
58
59
62
64
68
70
72
75
76
79
82
88
92
96
97
103
103
102
101
101
102
104
105
98
100
102
103
103
101
98
96
98
95
90
85
82
81
80
81
87
89
91
91
90
90
86
84
81
83
86
89
90
89
87
85
84
83
82
81
80
79
78
77
78
79
79
81
81
82
84
85
85
87
88
90
93
95
97
97
95
95
95
94
93
93
92
92
87
87
86
86
86
86
86
86
91
92
92
92
94
94
94
95
95
96
96
97
98
100
101
101
88
90
92
93
94
91
88
87
90
91
90
90
93
97
101
103
116
118
122
128
133
139
142
143
149
147
146
143
140
134
128
125
107
100
93
87
84
74
60
48
37
28
17
11
11
10
7
2
2
1
1
0
1
2
4
7
13
11
9
8
7
7
7
8
0
2
7
6
4
3
3
5
4
6
11
16
16
12
8
5
18
17
18
17
16
17
17
18
13
12
12
11
13
16
19
21
21
24
29
34
35
34
29
23
27
23
20
18
17
13
9
7
10
8
6
2
0
0
0
0
0
3
5
5
5
4
3
2
8
5
3
1
1
2
3
2
0
0
0
0
1
4
6
8
18
19
23
29
35
40
45
47
54
56
57
59
61
63

0
0
2
1
0
0
0
3
6
9
0
0
0
1
3
5
4
2
5
3
3
7
7
7
6
6
10
8
9
9
8
8
9
11
11
11
10
9
9
14
17
20
23
24
27
28
32
33
32
29
31
30
29
28
27
25
21
19
16
15
11
8
4
2
3
6
2
8
9
9
8
6
3
2
2
3
1
1
1
0
2
5
4
6
7
7
9
12
16
19
38
39
45
49
56
62
66
69
74
73
72
69
66
65
64
62
55
55
55
54
55
56
57
57
60
61
64
56
46
36
35
32
28
34
43
54
55
57
58
55
50
45
44
45
52
57
55
54
51
46
39
37
36
30
25
23
29
38
44
58
65
74
80
72
62
61
65
41
53
71
81
85
83
79
75
70
67
66
64
63
62
61
61
67
67
67
67
69
69
70
70
73
74
76
78
80
82
83
84
93
91
86
84
83
85
87
91
91
93
93
92
89
86
86
85
74
74
72
70
67
65
65
64
67
67
66
64
62
61
61
61
61
62
63
66
70
72
75
77
81
83
88
93
98
104
107
108
120
122
127
133
139
146
149
150
154
154
156
157
159
163
164
165
164
163
160
153
142
126
111
98
77
63
45
33
24
18
7
0
7
7
6
4
4
2
0
0
1
0
0
0
0
2
5
7
0
0
0
1
2
3
0
0
4
2
2
4
5
5
4
2
7
8
7
6
5
6
6
7
5
6
5
5
5
10
13
16
20
19
22
25
26
26
27
24
24
24
23
24
22
21
19
17
12
11
8
4
2
1
2
6
2
8
9
8
8
6
3
2
3
2
3
1
3
2
3
6
5
6
7
7
10
12
17
19
43
44
50
54


133
133
128
118
109
97
85
77
73
59
60
62
64
63
60
57
53
55
55
53
53
54
54
54
53
56
57
57
59
62
63
64
65
61
61
59
56
55
53
50
49
46
44
43
39
36
35
34
33
27
26
25
23
21
18
16
16
20
20
19
18
17
15
15
14
13
13
12
12
11
10
9
9
10
11
11
13
14
17
18
18
23
26
29
34
40
44
48
49
60
67
59
62
79
78
86
120
119
145
167
158
175
227
215
251
154
167
243
248
192
105
247
233
210
202
171
159
139
117
96
79
52
44
63
59
58
46
38
50
43
38
31
20
10
6
6
8
1
2
1
1
0
0
1
0
3
3
4
5
6
8
7
7
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
4
4
4
3
3
3
3
1
0
1
1
3
4
6
7
8
1
1
1
1
3
3
3
3
2
3
3
4
4
5
5
5
17
17
19
21
23
27
31
35
44
50
61
70
80
90
96
100
109
110
110
109
110
109
109
107
105
104
102
102
101
101
101
101
94
94
94
58
58
55
55
57
62
67
70
73
79
87
98
109
118
125
128
137
134
129
125
121
121
121
122
128
131
137
142
144
146
145
144
148
146
145
143
140
140
138
135
132
125
116
103
92
80
74
69
58
60
62
64
63
62
57
54
56
54
54
54
53
53
54
54
56
57
58
59
60
61
63
64
58
58
55
53
52
49
47
46
40
40
39
37
34
32
31
31
24
24
22
20
18
15
14

80
82
69
70
72
72
73
75
77
78
80
80
79
78
77
75
75
75
81
80
78
74
71
68
64
62
56
55
56
54
54
54
54
54
56
59
62
44
41
36
30
28
27
26
27
31
33
33
34
36
36
36
37
46
47
51
59
63
60
49
42
32
34
40
52
68
81
86
86
89
88
86
85
83
80
78
76
75
74
71
70
70
69
70
69
85
85
84
83
83
82
83
83
80
80
79
78
76
75
73
73
64
64
72
54
65
79
56
56
42
37
33
29
28
29
29
31
42
40
38
35
33
29
25
24
13
13
15
14
11
9
8
10
6
2
5
11
10
2
0
0
3
5
8
10
10
9
6
4
6
6
7
6
7
9
9
10
15
16
19
22
25
28
30
32
41
37
46
52
55
58
52
161
58
232
142
82
66
75
22
15
21
17
6
22
0
35
38
44
35
81
195
37
5
12
0
28
19
38
24
38
37
90
214
229
241
245
248
253
255
255
233
48
98
255
254
238
195
202
218
209
211
227
228
121
24
119
246
237
239
189
109
41
22
35
44
43
57
69
78
83
78
59
52
62
61
60
59
57
55
53
52
51
54
53
51
49
50
53
56
58
54
54
54
54
54
54
54
56
57
60
63
65
69
74
76
77
84
84
85
84
84
84
83
83
80
78
77
76
74
74
73
74
73
72
70
68
65
61
59
58
57
55
53
51
52
54
58
60
52
55
58
41
39
33
28
26
24
24
25
28
30
30
33
35
38
39
40
48
50
55
60

221
133
139
238
255
248
249
162
33
48
37
2
13
16
0
13
12
33
13
48
93
154
204
32
32
136
193
110
51
43
3
13
43
32
24
43
222
211
51
14
58
104
137
158
165
170
186
219
241
118
40
44
55
39
37
45
48
62
42
35
48
45
54
57
58
60
64
69
71
73
74
70
65
69
70
49
17
4
13
48
53
60
67
71
71
70
68
66
65
62
59
56
52
51
48
46
46
45
45
45
42
42
42
43
43
44
45
47
48
49
50
54
54
54
60
55
50
50
52
52
47
44
42
40
37
35
33
33
35
35
40
43
51
60
63
56
41
32
20
23
29
46
72
100
117
126
126
126
125
124
123
120
119
119
123
113
102
99
102
102
99
94
104
96
91
95
105
103
91
77
44
0
0
9
6
0
1
28
9
13
29
0
0
11
0
41
16
0
0
0
0
18
28
16
0
0
0
1
15
23
16
4
10
0
0
9
0
0
18
9
22
2
10
17
11
1
3
36
48
12
0
0
5
41
27
24
0
5
7
4
7
20
35
45
49
48
48
49
51
53
51
51
57
55
53
51
50
50
53
56
49
72
47
61
29
88
190
28
0
137
189
17
1
92
254
220
239
236
242
226
252
249
211
147
220
40
6
0
176
245
241
119
59
60
45
18
15
0
0
0
6
33
23
25
22
15
40
61
12
71
65
29
5
7
3
19
5
0
29
44
56
119
151
67
50
17
0
0
75
140
156
148
234
214
239
91
40
51
43

64
63
64
65
68
71
73
76
77
78
76
78
53
28
156
169
128
158
47
48
156
165
123
73
44
36
38
38
39
37
33
29
26
32
30
28
26
23
20
17
17
32
5
86
234
243
103
13
23
18
8
9
0
4
15
42
41
19
16
15
17
20
18
12
6
4
24
31
44
70
222
122
2
116
244
79
63
239
240
219
234
205
101
217
98
93
0
13
0
0
34
4
29
0
41
96
63
53
49
16
0
0
23
57
41
61
75
79
71
75
82
71
49
58
55
41
16
0
0
0
5
57
55
56
57
56
55
55
54
54
51
51
51
51
51
52
50
54
57
60
93
94
92
93
90
86
84
81
71
69
62
54
46
39
33
29
26
28
25
20
24
31
29
25
26
26
25
25
21
20
33
49
31
4
0
9
28
62
79
64
10
0
14
25
16
20
34
30
10
12
32
38
18
13
17
3
16
24
19
17
18
2
0
21
5
13
0
26
0
0
16
19
13
0
18
26
41
9
13
0
28
20
16
25
11
19
6
1
8
17
28
0
13
6
0
29
0
3
27
0
0
0
34
32
10
0
0
14
25
15
14
27
7
0
0
22
56
41
14
20
7
2
3
20
46
65
68
63
80
78
77
75
71
69
65
64
68
68
69
70
73
74
77
77
97
77
66
83
53
83
206
221
188
179
153
72
61
34
11
33
23
27
31
34
34
29
25
22
33
18
17
15
4
12
20
7
27
9
37
235
228
5
19
5
10
0
0
0
0
9
17
24
8
14
22
32
35
28
18
11
37
53
54
59
71


25
31
21
5
11
20
23
20
10
3
7
0
15
32
52
72
86
92
91
71
72
72
75
77
80
80
82
79
78
78
75
74
74
71
71
73
64
75
63
50
88
70
0
134
170
68
58
50
37
30
3
23
20
5
0
8
35
27
0
10
4
0
1
12
16
14
9
12
14
13
4
0
0
8
19
19
29
22
7
5
1
0
3
13
5
3
8
14
14
13
8
44
69
0
81
73
31
45
49
50
160
153
179
91
5
129
56
22
14
0
19
4
25
0
5
87
44
53
18
46
22
20
141
40
60
13
6
0
23
21
29
69
18
0
13
1
2
7
21
41
5
79
46
71
2
0
64
0
5
8
5
4
8
10
10
26
34
37
29
21
15
13
10
13
18
24
20
19
16
13
10
9
7
4
1
0
0
0
0
1
1
1
1
5
10
14
13
11
12
22
11
19
23
22
15
7
13
26
0
26
33
21
14
8
6
14
24
0
0
3
20
44
47
2
15
41
48
26
5
8
15
13
1
0
2
9
20
31
40
45
58
40
76
28
0
33
51
11
69
55
72
50
11
0
32
14
42
6
51
21
42
64
3
24
55
49
113
60
22
34
12
0
51
44
43
63
79
61
42
48
14
0
0
13
16
0
13
6
0
13
28
35
26
2
0
0
0
0
17
35
58
76
88
95
67
68
70
72
76
78
80
81
75
74
72
71
70
69
67
66
80
50
69
62
25
125
155
184
216
112
7
69
23
6
30
3
14
0
0
26
31
9
0
6
0
0
8
18
25
21
9
0
3
9
10
2
0
0
9
25
13
19
15
11
10
9
10
15
7
8
14
13
0
0
17
57
49


33
46
96
107
103
96
108
130
123
85
64
44
12
48
32
17
11
16
53
46
34
42
28
37
44
59
86
98
108
46
43
43
44
43
41
37
32
34
33
31
29
27
25
24
23
20
22
23
25
27
29
30
31
32
30
29
27
24
23
21
20
13
14
4
8
3
2
13
23
1
110
47
129
241
229
152
43
21
14
0
6
11
13
17
4
0
0
9
13
12
10
9
9
0
8
22
27
24
8
0
9
1
33
56
73
63
36
20
0
4
4
5
5
3
1
8
21
45
42
124
72
70
96
85
65
164
133
6
96
76
114
23
44
70
11
10
0
15
22
11
17
58
58
38
0
8
26
28
47
3
35
98
76
49
103
112
69
22
31
58
35
9
25
8
0
2
41
64
56
43
36
29
21
8
5
3
6
12
15
15
18
24
18
10
4
0
0
20
40
4
4
4
41
40
39
40
42
45
51
54
51
52
51
53
52
51
50
50
50
60
73
85
89
88
84
82
95
98
98
88
66
41
24
18
33
34
52
83
103
103
93
84
68
56
38
20
11
11
19
26
0
29
68
93
106
108
88
63
35
28
41
27
41
12
32
53
44
71
91
106
90
79
60
70
62
69
81
89
90
67
61
61
57
73
109
107
124
148
143
138
143
138
120
96
80
64
48
37
17
31
38
66
66
96
110
117
93
81
93
94
92
95
81
72
49
41
35
35
41
43
38
32
34
31
28
25
21
18
16
14
14
16
16
19
21
24
25
26
24
23
22
21
19
15
14
13
4
6
4


83
86
84
81
76
73
70
69
70
72
78
80
84
88
90
92
94
95
92
97
98
98
92
83
74
67
57
58
63
70
79
90
99
103
106
115
126
130
129
126
123
123
110
109
106
104
99
97
95
95
98
98
98
98
96
95
94
93
102
92
97
115
129
129
115
107
111
104
106
97
89
69
101
99
110
87
119
113
132
142
136
138
137
138
140
146
150
153
155
154
139
138
132
124
113
102
93
88
75
72
66
56
45
30
18
11
3
3
3
1
1
0
0
0
2
1
4
7
10
11
13
11
10
9
7
7
5
3
4
6
7
8
8
7
5
4
3
2
4
5
7
7
6
3
0
0
0
0
0
1
1
0
0
0
0
0
16
0
4
0
28
31
30
40
24
4
34
37
31
82
47
114
123
115
63
22
35
39
27
47
48
39
36
17
0
5
0
15
22
16
17
25
30
23
20
33
52
67
82
94
102
104
101
114
119
102
79
62
53
53
83
85
111
144
133
92
79
97
83
102
99
92
93
69
32
24
23
12
8
27
43
33
31
54
96
69
36
69
93
85
103
103
55
19
14
21
59
100
71
112
147
134
131
127
102
69
66
83
54
11
0
0
29
57
26
20
14
14
14
103
90
83
93
98
85
82
97
86
84
80
78
76
73
72
72
79
80
83
88
90
91
92
95
89
95
97
97
93
84
74
70
58
58
62
66
74
83
91
94
99
93
97
110
128
131
116
101
106
102
98
94
93
95
98
101
95
95

39
71
20
2
5
18
13
24
19
39
153
195
180
172
143
133
137
144
213
185
172
167
183
61
1
0
32
4
27
23
23
6
22
65
109
142
126
120
129
134
125
122
129
108
71
65
101
121
106
104
123
125
137
138
133
131
129
138
156
140
139
136
131
127
124
122
121
116
116
116
75
80
66
48
79
115
108
115
113
110
107
102
98
95
95
96
102
103
102
101
97
92
87
84
84
86
86
85
82
75
70
66
67
62
57
49
45
46
50
54
65
74
81
87
90
90
87
86
96
96
95
95
95
95
95
95
97
98
97
96
94
93
91
92
95
94
92
91
89
89
92
94
94
89
96
90
83
78
82
123
130
99
59
92
98
108
103
113
110
109
106
106
107
108
110
112
117
118
118
119
119
118
115
111
90
81
72
59
46
34
25
18
12
12
10
9
5
4
0
0
0
0
0
0
1
4
6
7
10
10
8
8
6
6
4
5
0
0
3
5
7
9
11
11
13
14
15
16
17
17
14
11
10
9
11
16
18
19
19
19
24
15
23
37
24
0
0
5
34
40
25
0
0
22
32
24
18
9
0
27
32
56
70
76
98
107
110
107
105
106
93
78
55
63
45
44
64
113
21
1
13
14
0
32
85
32
37
63
0
7
33
18
27
55
86
171
195
195
210
159
125
110
112
215
182
163
180
168
139
37
18
7
15
0
21
6
43
38
29
34
54
96
130
129
121

58
69
75
80
78
78
63
49
22
21
0
10
29
45
64
55
33
18
23
41
37
34
29
27
25
27
23
17
9
9
11
39
43
59
64
159
175
168
158
144
73
64
64
64
71
100
105
101
122
118
86
106
68
88
94
102
113
104
96
103
98
102
102
103
104
106
107
108
109
110
112
116
118
122
125
128
130
135
135
138
139
142
145
148
150
153
154
156
156
157
157
157
157
143
143
143
126
135
136
125
123
132
136
131
131
128
122
114
102
91
81
76
71
72
71
70
67
61
55
53
58
62
61
56
55
60
66
70
78
64
54
39
25
33
54
61
54
55
58
63
68
73
76
79
78
78
79
83
88
96
104
113
120
124
127
128
127
124
122
121
109
104
97
90
84
80
78
76
79
77
73
81
76
83
63
84
98
100
56
77
78
74
80
81
78
81
83
86
89
92
93
94
100
100
101
104
106
109
110
111
111
109
107
105
103
101
98
98
72
72
71
69
66
64
59
54
51
46
41
39
35
33
32
32
15
14
15
15
16
17
16
19
17
20
24
26
23
19
12
8
7
8
10
12
16
18
19
20
18
17
15
12
10
9
8
6
15
14
11
8
5
4
2
2
3
4
5
7
11
14
20
22
34
40
48
60
71
78
82
80
81
69
24
12
12
0
32
50
46
60
64
32
25
48
51
48
40
35
32
31
32
31
22
15
15
22
31
41
54
53

31
37
46
58
71
81
87
100
98
95
90
85
78
73
68
60
61
63
64
68
71
73
74
84
88
94
102
110
114
116
114
105
102
100
98
99
102
104
105
95
94
93
91
90
88
86
86
89
89
89
91
86
73
52
38
35
40
56
77
96
106
107
104
104
106
89
117
121
131
135
136
131
135
130
131
135
114
105
134
125
100
54
93
113
120
130
133
125
126
129
132
131
130
127
126
130
131
133
136
138
142
142
144
148
148
148
150
152
153
154
156
156
157
157
159
158
159
160
159
157
157
157
148
151
156
160
164
167
167
167
166
158
149
134
117
102
87
81
69
75
77
77
79
82
83
84
70
87
102
111
123
138
143
139
132
120
106
93
86
77
69
59
49
56
60
59
63
70
70
62
71
74
75
82
90
101
113
122
130
132
135
134
131
125
122
119
115
112
108
103
97
91
87
83
90
80
85
80
84
88
72
70
86
98
59
78
81
84
88
84
90
93
94
96
98
98
99
99
103
105
106
110
112
115
117
117
124
124
123
123
122
123
123
123
117
117
116
114
113
111
108
106
95
88
80
71
62
52
45
42
27
26
26
24
20
18
16
15
15
18
23
27
28
24
20
17
19
19
18
18
16
17
17
17
25
30
38
46
59
70
81
88
104
103
103
100
95
89